#!/bin/sh
#
# chkconfig: 2345 20 80
# /etc/rc.d/init.d/alilua
#
### BEGIN INIT INFO
# Provides:          alilua
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:    $remote_fs $named $network $time
# Required-Stop:     $remote_fs $named $network $time
# Short-Description: Start aLiLua Web Server daemons at boot time
# Description:       Enable aLiLua Web Server services.
### END INIT INFO


case "$1" in
  start)
    /usr/local/alilua/alilua bind=80 daemon;;
  restart)
    exec /bin/killall alilua > /dev/null;
    sleep 1;
    /usr/local/alilua/alilua bind=80 daemon;;
  stop)
    exec /bin/killall alilua > /dev/null;;
esac
